import os
import json
import time
from typing import List, Tuple, Optional, Dict
from datetime import datetime

# Глобальные переменные
client = None
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")

# Импорты сканеров с graceful fallback
try:
    from scanners.sql_scanner import scan_sql_injection
    from scanners.xss import scan_xss
    from scanners.csrf_scanner import check_csrf_protection
    from scanners.ssrf_scanner import scan_ssrf
    from scanners.network_scanner import scan_network_segmentation
    print("✅ Все сканеры загружены")
except ImportError as e:
    print(f"⚠️ Ошибка импорта сканеров: {e}")
    # Fallback функции
    def scan_sql_injection(url): return False
    def scan_xss(url): return False
    def check_csrf_protection(url): return False
    def scan_ssrf(url): return False
    def scan_network_segmentation(url): return []

def ai_analysis(vulnerabilities: List[str]) -> Tuple[str, str]:
    """
    Простой fallback AI-анализ (без OpenAI для стабильности).
    """
    if not vulnerabilities:
        return (
            "✅ No critical vulnerabilities detected.",
            "✅ Критических уязвимостей не найдено."
        )
    
    vulns_str = ", ".join(vulnerabilities)
    return (
        f"🚨 Found: {vulns_str}. Prioritize fixes: HIGH risk.",
        f"🚨 Обнаружено: {vulns_str}. Приоритет исправления: ВЫСОКИЙ."
    )

def full_scan(url: str) -> Dict:
    """
    Полное сканирование с метриками.
    """
    print(f"🔍 Scanning {url}...")
    results = {
        "timestamp": datetime.now().isoformat(),
        "target": url,
        "vulnerabilities": [],
        "metrics": {},
        "ai_analysis": {"en": "", "ru": ""}
    }
    
    t0 = time.time()
    try:
        # Сканирование
        scans = [
            ("SQL Injection", scan_sql_injection(url)),
            ("XSS", scan_xss(url)),
            ("CSRF", check_csrf_protection(url)),
            ("SSRF", scan_ssrf(url))
        ]
        
        for name, detected in scans:
            status = '🟡 DETECTED' if detected else '🟢 CLEAN'
            print(f"  {name}: {status}")
            if detected:
                results["vulnerabilities"].append(name)
        
        net_issues = scan_network_segmentation(url)
        if net_issues:
            results["vulnerabilities"].extend([f"Network: {issue}" for issue in net_issues])
        
        # Метрики
        results["metrics"] = {
            "scan_time": round(time.time() - t0, 2),
            "vuln_count": len(results["vulnerabilities"]),
            "security_score": max(0, 100 - len(results["vulnerabilities"]) * 20)
        }
        
        # AI
        results["ai_analysis"]["en"], results["ai_analysis"]["ru"] = ai_analysis(
            results["vulnerabilities"]
        )
        
    except KeyboardInterrupt:
        print("\n👋 Сканирование прервано пользователем")
        results["status"] = "interrupted"
    except Exception as e:
        print(f"💥 Ошибка при сканировании: {str(e)}")
        results["error"] = str(e)
    
    return results

def generate_reports(results: Dict) -> None:
    """Генерирует подробные MD/JSON/TXT отчеты."""
    ts = datetime.now().strftime("%Y%m%d_%H%M")
    os.makedirs("reports", exist_ok=True)
    
    vulns = results["vulnerabilities"]
    metrics = results["metrics"]
    
    # ПОДРОБНЫЙ Markdown EN
    detailed_en = f"""# 🛡️ WebSecAI Professional Report v2.0

## 🎯 Target: {results["target"]}
**Timestamp:** {results["timestamp"]}  
**Duration:** {metrics["scan_time"]}s

## 📊 Executive Summary
| Metric | Value |
|--------|-------|
| **Vulnerabilities** | {len(vulns)} |
| **Security Score** | {metrics["security_score"]}/100 |
| **Risk Level** | {'🔴 CRITICAL' if len(vulns)>=3 else '🟡 HIGH' if len(vulns)==2 else '🟢 MEDIUM'} |

## 🚨 Detailed Findings
{vulns and "\\n".join([f"• **{v}** - OWASP Top 10" for v in vulns]) or "✅ No vulnerabilities detected"}

## 🤖 AI Security Analysis
{results["ai_analysis"]["en"]}

---
**Generated by** WebSecAI Suite | GitHub: credibility-index/WebSec-AI
"""
    
    # ПОДРОБНЫЙ Markdown RU  
    detailed_ru = f"""# 🛡️ Профессиональный Отчёт WebSecAI v2.0

## 🎯 Цель: {results["target"]}
**Время:** {results["timestamp"]}  
**Длительность:** {metrics["scan_time"]}с

## 📊 Сводка
| Метрика | Значение |
|---------|----------|
| **Уязвимостей** | {len(vulns)} |
| **Оценка** | {metrics["security_score"]}/100 |
| **Риск** | {'🔴 КРИТИЧЕСКИЙ' if len(vulns)>=3 else '🟡 ВЫСОКИЙ' if len(vulns)==2 else '🟢 СРЕДНИЙ'} |

## 🚨 Детальные Результаты
{vulns and "\\n".join([f"• **{v}** - OWASP Top 10" for v in vulns]) or "✅ Уязвимости не обнаружены"}

## 🤖 AI Анализ
{results["ai_analysis"]["ru"]}

---
**Сгенерировано** WebSecAI Suite | t.me/likeluv
"""
    
    # TXT для логов/Telegram
    txt_report = f"""WebSecAI SCAN REPORT {ts}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

TARGET: {results["target"]}
VULNS: {len(vulns)} | SCORE: {metrics["security_score"]}/100
TIME: {metrics["scan_time"]}s

FINDINGS:
{chr(10).join(vulns) or "✅ CLEAN"}

AI: {results["ai_analysis"]["en"][:200]}...

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
GitHub: credibility-index/WebSec-AI
"""
    
    # Сохранение ВСЕХ форматов
    formats = [
        (f"websec_en_{ts}.md", detailed_en),
        (f"websec_ru_{ts}.md", detailed_ru),
        (f"websec_full_{ts}.json", json.dumps(results, ensure_ascii=False, indent=2)),
        (f"websec_txt_{ts}.txt", txt_report)
    ]
    
    for filename, content in formats:
        with open(f"reports/{filename}", "w", encoding="utf-8") as f:
            f.write(content)
    
    print(f"✅ 4 отчёта сохранены:")
    print(f"   📄 reports/websec_en_{ts}.md")
    print(f"   📄 reports/websec_ru_{ts}.md") 
    print(f"   📊 reports/websec_full_{ts}.json")
    print(f"   📝 reports/websec_txt_{ts}.txt")


def main():
    """CLI вход."""
    print("\n=== 🛡️ WebSecAI v2.0 ===")
    target = input("🎯 URL: ").strip()
    if not target.startswith(('http://', 'https://')):
        print("❌ Invalid URL")
        return
    
    results = full_scan(target)
    print(f"\n📊 Vulns: {len(results['vulnerabilities'])} | Score: {results['metrics']['security_score']}")
    generate_reports(results)

def scan_crypto_wallet(address: str) -> bool:
    """Демо крипто-сканер."""
    invalid_patterns = ['0x0*', 'bc1q0*']
    return any(pattern in address for pattern in invalid_patterns)

if __name__ == "__main__":
    try:
        os.makedirs("reports", exist_ok=True)
        main()
    except Exception as e:
        print(f"💥 Error: {str(e)}")
