import os
from datetime import datetime
from typing import Any, Dict, List, Optional, Tuple

COMPANY_NAME = os.environ.get("WEBSECAI_COMPANY", "WebSecAI")

VULN_SEVERITY: Dict[str, str] = {
    "SQL INJECTION": "Critical",
    "XSS": "High",
    "CSRF MISSING": "High",
    "SSRF": "High",
    "SSTI": "High",
    "CORS": "Medium",
    "HOST HEADER": "Medium",
    "Server Version Leak": "Low",
    "Technology Leak": "Low",
    "Missing HSTS": "Medium",
    "CRITICAL": "Critical",
    "403 Bypass": "High",
}
OWASP_CATEGORY: Dict[str, str] = {
    "SQL INJECTION": "A03:2021 Injection",
    "XSS": "A03:2021 Injection",
    "CSRF MISSING": "A01:2021 Broken Access Control",
    "SSRF": "A10:2021 Server-Side Request Forgery",
    "SSTI": "A03:2021 Injection",
    "CORS": "A05:2021 Security Misconfiguration",
    "HOST HEADER": "A05:2021 Security Misconfiguration",
}


def _severity_for(vuln: str) -> str:
    for key, sev in VULN_SEVERITY.items():
        if key.upper() in (vuln or "").upper():
            return sev
    return "Medium"


def _category_for(vuln: str) -> str:
    for key, cat in OWASP_CATEGORY.items():
        if key.upper() in (vuln or "").upper():
            return cat
    return "Other"

def html_report(scan_result: Dict[str, Any], title: Optional[str] = None) -> str:
    title = title or f"Security Report — {scan_result.get('target', 'Target')}"
    vulns = scan_result.get("vulnerabilities", [])
    flags = scan_result.get("flags", [])
    metrics = scan_result.get("metrics", {})
    ai_en = (scan_result.get("ai_analysis") or {}).get("en", "")
    ai_ru = (scan_result.get("ai_analysis") or {}).get("ru", "")
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
body {{ font-family: system-ui, sans-serif; max-width: 900px; margin: 0 auto; padding: 2rem; color: #1e293b; }}
h1 {{ color: #0f172a; border-bottom: 2px solid #0ea5e9; padding-bottom: 0.5rem; }}
.meta {{ color: #64748b; font-size: 0.9rem; margin-bottom: 1.5rem; }}
.vuln {{ background: #fef2f2; border-left: 4px solid #dc2626; padding: 0.75rem; margin: 0.5rem 0; }}
.flag {{ background: #f0fdf4; border-left: 4px solid #16a34a; padding: 0.75rem; margin: 0.5rem 0; }}
.metrics {{ display: flex; gap: 1rem; margin: 1rem 0; flex-wrap: wrap; }}
.metrics span {{ background: #f1f5f9; padding: 0.5rem 1rem; border-radius: 6px; }}
footer {{ margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #e2e8f0; color: #64748b; font-size: 0.85rem; }}
</style>
</head>
<body>
<h1>{title}</h1>
<p class="meta">Target: {scan_result.get('target', '')} · Date: {scan_result.get('timestamp', '')} · {COMPANY_NAME}</p>
<div class="metrics">
<span>Score: {metrics.get('score', 0)}/100</span>
<span>Findings: {metrics.get('vuln_count', 0)}</span>
<span>Scan time: {metrics.get('scan_time', 0)}s</span>
</div>
<h2>Findings by severity</h2>
"""
    if vulns:
        by_sev: Dict[str, List[str]] = {}
        for v in vulns:
            sev = _severity_for(v)
            by_sev.setdefault(sev, []).append(v)
        for sev in ("Critical", "High", "Medium", "Low"):
            if sev in by_sev:
                html += f"<h3>{sev}</h3>\n"
                for v in by_sev[sev]:
                    cat = _category_for(v)
                    html += f'<div class="vuln"><span style="color:#64748b;font-size:0.85rem;">[{cat}]</span> {v}</div>\n'
    else:
        html += "<p>No vulnerabilities detected.</p>\n"
    if flags:
        html += "<h2>Flags found</h2>\n"
        for f in flags:
            flag_val = f.get("flag", f) if isinstance(f, dict) else f
            html += f'<div class="flag"><code>{flag_val}</code></div>\n'
    html += "<h2>AI Analysis</h2>\n"
    html += f"<p><strong>EN:</strong> {ai_en}</p>\n"
    html += f"<p><strong>RU:</strong> {ai_ru}</p>\n"
    html += f"<footer>Generated by {COMPANY_NAME} · {datetime.utcnow().isoformat()}Z</footer>\n</body>\n</html>"
    return html


def pdf_report(scan_result: Dict[str, Any], title: Optional[str] = None) -> Optional[bytes]:
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
        from reportlab.lib import colors
    except ImportError:
        return None

    vulns = scan_result.get("vulnerabilities", [])
    metrics = scan_result.get("metrics", {})
    ai_ru = (scan_result.get("ai_analysis") or {}).get("ru", "")
    target = scan_result.get("target", "")
    ts = scan_result.get("timestamp", "")

    import io
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, rightMargin=2*cm, leftMargin=2*cm, topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph(title or "Security Report", styles["Title"]))
    story.append(Spacer(1, 0.5*cm))
    story.append(Paragraph(f"Target: {target}", styles["Normal"]))
    story.append(Paragraph(f"Date: {ts}", styles["Normal"]))
    story.append(Paragraph(f"Score: {metrics.get('score', 0)}/100 · Findings: {metrics.get('vuln_count', 0)}", styles["Normal"]))
    story.append(Spacer(1, 1*cm))

    story.append(Paragraph("Findings", styles["Heading2"]))
    if vulns:
        data = [["Severity", "Finding"]]
        for v in vulns:
            data.append([_severity_for(v), v[:80] + ("..." if len(v) > 80 else "")])
        t = Table(data, colWidths=[4*cm, 12*cm])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0ea5e9")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ]))
        story.append(t)
    else:
        story.append(Paragraph("No vulnerabilities detected.", styles["Normal"]))
    story.append(Spacer(1, 1*cm))

    story.append(Paragraph("AI Analysis", styles["Heading2"]))
    story.append(Paragraph(ai_ru or "—", styles["Normal"]))
    story.append(Spacer(1, 0.5*cm))
    story.append(Paragraph(f"Generated by {COMPANY_NAME}", styles["Normal"]))

    doc.build(story)
    return buf.getvalue()
